config/routes.rb
Rails.application.routes.draw do

  resources :bords, only: [:create, :show], param: :uniq_link do
    resources :lists, only: [:new, :create, :destroy] do
      resources :cards, only: [:new, :create, :destroy, :edit, :update] do
        put '/tie', to: 'cards#tie'
      end
    end
    get '/short', to: 'bords#short_show'
  end

  root to: 'root#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bord.rb
class Bord < ApplicationRecord

  validates_presence_of :title, :uniq_link
  validates_uniqueness_of :uniq_link

  has_many :lists, dependent: :restrict_with_exception, validate: false

  def to_param
    uniq_link
  end
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :list, validate: false
  validates_presence_of :list, :title


end

app/models/list.rb
class List < ApplicationRecord

  belongs_to :bord, validate: false
  validates_presence_of :bord, :title

  has_many :cards, dependent: :destroy, validate: false

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
  def record_not_found
    render partial: 'errors/page_not_found', status: :not_found
  end
end

app/controllers/bords_controller.rb
class BordsController < ApplicationController
  include ContrBlock::BordHelpers
  before_action(only: [:show]) { get_bord_by_key(:uniq_link, [:lists, lists: [:cards]]) }
  before_action(only: [:short_show]) { get_bord_by_key(:bord_uniq_link, [:lists, lists: [:cards]]) }
  before_action :set_bord_to_enc_cookies, only: [:show]

  layout false, only: [:short_show]

  def create
    @bord = BordCreateService.new(bord_params).()

    if @bord.persisted?
      redirect_to bord_path(uniq_link: @bord.uniq_link)
    else
      render 'bords/new'
    end
  end

  def show
  end

  def short_show
    render partial: 'bords/table_data'
  end

  private
  def bord_params
    params.require(:bord).permit(:title)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  include ContrBlock::BordHelpers

  before_action { get_bord_by_key(:bord_uniq_link) }
  before_action :get_list
  before_action :get_card, only: [:edit, :update, :destroy]
  before_action(only: [:tie]) { get_card_with_check_bord }

  def create
    @card = CardMod::CreateService.new(@bord, @list).(card_params)
    if @card.persisted?
      redirect_to bord_path(uniq_link: @bord.uniq_link), notice: I18n.t("controllers.cards.create.successful_msg")
    else
      render 'cards/new'
    end
  end

  def edit
    render 'cards/edit'
  end

  def update
    if CardMod::UpdateService.new(@bord, @card).(card_params)
      redirect_to bord_path(uniq_link: @bord.uniq_link), notice: I18n.t("controllers.cards.update.successful_msg")
    else
      render 'cards/edit'
    end
  end

  def new
    @card = @list.cards.new
  end

  def destroy
    CardMod::DestroyService.new(@bord, @card).call
    redirect_to bord_path(uniq_link: @bord.uniq_link), notice: I18n.t("controllers.cards.destroy.successful_msg")
  end

  def tie
    head((CardMod::TieService.new(@list, @card).()) ? :ok : :bad_request)
  end

  private
  def get_list
    @list = @bord.lists.find_by!(id: params[:list_id])
  end

  def get_card
    @card = @list.cards.where(id: params[:id]).first
    if @card.blank?
      redirect_to bord_path(uniq_link: @bord.uniq_link), alert: I18n.t("controllers.cards.not_found")
    end
  end

  def get_card_with_check_bord
    @card = Card.joins(:list).where(lists: { bord: @bord }).find(params[:card_id])
  end

  def card_params
    params.require(:card).permit(:title)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  include ContrBlock::BordHelpers
  before_action { get_bord_by_key(:bord_uniq_link) }
  before_action :get_list, only: [:destroy]

  def new
    @list = @bord.lists.new
  end

  def create
    @list = ListMod::CreateService.new(@bord).(list_params)
    if @list.persisted?
      redirect_to bord_path(uniq_link: @bord.uniq_link), notice: I18n.t("controllers.lists.create.successful_msg")
    else
      render 'lists/new'
    end
  end

  def destroy
    ListMod::DestroyService.new(@bord, @list).()
    redirect_to bord_path(uniq_link: @bord.uniq_link), notice: I18n.t("controllers.lists.destroy.successful_msg")
  end

  private
  def list_params
    params.require(:list).permit(:title)
  end

  def get_list
    @list = @bord.lists.where(id: params[:id]).first
    if @list.blank?
      redirect_to bord_path(uniq_link: @bord.uniq_link), alert: I18n.t("controllers.lists.not_found")
    end
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
    @bord = Bord.new
    render 'bords/new'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bords_helper.rb
module BordsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/bords/_table_data.html.erb
<div>
  <div class="columns">
    <% @bord.lists.each do |list| %>
        <div class="column" list_id="<%= list.id %>">
          <div>
            <div class="listrowleft"> <%= list.title %> </div>
            <div class="listright">
              <%= button_to "X", [@bord, list], {method: :delete, data: { confirm: I18n.t('views.bord.lists.delete.confirm_msg') }}%>
            </div>
          </div>
          <div>
            <%= button_to I18n.t('views.bord.show.create_card_bt'), new_bord_list_card_path(@bord, list), {method: :get} %>
          </div>
          <% list.cards.each do |card| %>
              <div class="card">
                <div card_id="<%= card.id %>" list_id="<%= card.list_id %>" class="draggable">
                  <p> <%= card.title %> </p>
                </div>
                <div class="listright">
                  <%= button_to "E", edit_bord_list_card_path(@bord, list, card), {method: :get} %>
                </div>
                <div class="listright">
                  <%= button_to "X", [@bord, list, card], {method: :delete, data: { confirm: I18n.t('views.bord.cards.delete.confirm_msg') }}%>
                </div>
              </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/bords/new.html.erb
<%= form_with(model: @bord, local: true) do |f| %>
    <%= render partial: 'errors/model_form_show', locals: {some_model: @bord} %>
    <%= f.text_field :title %>
    <%= f.submit I18n.t("views.bord.new.create_bt") %>
<% end %>

app/views/bords/show.html.erb
<div hidden="true" id="bord_uniq_link" uniq_link="<%= @bord.uniq_link %>"></div>

<div>
  <p> <%= I18n.t('views.bord.show.bord_short_title') %> : <%= bord_path(uniq_link: @bord.uniq_link) %> </p>
</div>

<div>
  <%= button_to I18n.t('views.bord.show.create_list_bt'), new_bord_list_path(@bord), {method: :get} %>
</div>


<div id="bord_table_data">
  <%= render 'bords/table_data' %>
</div>

app/views/cards/edit.html.erb
<%= form_with(model: [@bord, @list, @card], local: true) do |f| %>
    <%= render partial: 'errors/model_form_show', locals: {some_model: @card} %>
    <%= f.text_field :title %>
    <%= f.submit I18n.t("views.card.update.apply_bt") %>
<% end %>

app/views/cards/new.html.erb
<%= form_with(model: [@bord, @list, @card], local: true) do |f| %>
    <%= render partial: 'errors/model_form_show', locals: {some_model: @card} %>
    <%= f.text_field :title %>
    <%= f.submit I18n.t("views.card.new.create_bt") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTrelloClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/new.html.erb
<%= form_with(model: [@bord, @list], local: true) do |f| %>
    <%= render partial: 'errors/model_form_show', locals: {some_model: @list} %>
    <%= f.text_field :title %>
    <%= f.submit I18n.t("views.list.new.create_bt") %>
<% end %>